### ISSUE TITLE
How about a static redirect version?

### ISSUE THREAD

**Issue by NathanielHill** [now-examples/redirect#13]
A common complaint is having to use a dynamic instance to redirect from a naked domain to `www`. I found a way around this using the new `serve-handler` options like so:

Put the following in `now.json`:
```
{
    "type": "static",
    "static":
    {
        "redirects":
        [
            {
                "source": "/*",
                "destination": "https://<your-domain-here>"
            }
        ]
    }
}
```
Then:
`touch index.html` // Otherwise `now` complains
`now` // That's it!

Now, I'd love to be able to forward the path along to the new address as well.

Also, if there is any type of hook that we can use before deployment so that the destination can be set dynamically (say with an environment variable)... then we could have a version of this repository that didn't use an instance.

I made an example here: https://github.com/NathanielHill/now-static-redirect

**Comment by leo** [comment]
Great idea!

**Comment by NathanielHill** [comment]
@leo, I tried converting it to a Docker static build, and it seemed like that should work, but it looks like it ignores the `now.json` file that gets produced in `/public` and only uses the original `now.json` from the originating machine. Can you think of a way to accept a hostname dynamically, yet still produce a static deployment?

This is what I came up with so far: https://github.com/NathanielHill/now-static-redirect/tree/convert-to-docker-static

**Comment by NathanielHill** [comment]
I suppose, I could get nutty and create a Docker build that installed `now-cli` and used a token to do a static deployment from *within* the container. Doesn't seem like a good long-term approach, and it may mean that you have two deployments laying around.. with one in a possible error state even. :man_shrugging:

**Comment by NathanielHill** [comment]
@leo Is it possible to forward the path will doing a redirect with `serve-handler`?

For example, on Cloudflare one would be able to get the arguments from globs like so:

`https://example.com/*` -> `https://www.example.com/$1`

I didn't see any similar options in the `now.json` documentation. Is this possible?

**Comment by dan-kwiat** [comment]
@NathanielHill you can now do it like this:

```json
{
  "version": 2,
  "alias": ["www.your-domain.com"],
  "routes": [
    {
      "src": "/(.*)",
      "status": 301,
      "headers": { "Location": "https://your-domain.com/$1" }
    }
  ]
}
```

Official guide here: https://zeit.co/guides/redirect-from-www

Please could you update the README for future visitors?

**Comment by NathanielHill** [comment]
@dan-kwiat yeah, I've been doing this for months now. Didn't know it wasn't in the docs
