### ISSUE TITLE
Better readme

### ISSUE THREAD

**Issue by t0ker** [now-examples/redirect#5]
Hi,

Just got everything working, and it works like a charm.

It would be good if you could make the readme a bit more noob friendly ( :) )

Make it clear that the redirect instance is separate from main instance, and is only used for the redirect. 

Thanks

**Comment by TooTallNate** [comment]
@t0ker Nice idea! Would you care to try your hand at pull request?

**Comment by timneutkens** [comment]
@t0ker I've updated the readme. What I've also done is move the repository to now-examples. So it's an official example now 👌 👍
