### ISSUE TITLE
Improve REDIRECT_URL support

### ISSUE THREAD

**Issue by sergiodxa** [now-examples/redirect#7]
Right now we need to add the protocol and a trailing slash to the `REDIRECT_URL`.

> e.g. `https://zeit.co/` works but `zeit.co`, `https://zeit.co` or `zeit.co/` doesn't works

We need to support for not defining the protocol and the trailing slash, we could default to `http` and let the browser change to `https`

**Comment by TooTallNate** [comment]
@sergiodxa I believe this is fixed by https://github.com/now-examples/redirect/commit/42bbf09e6d8edce333d98a1f45c0a6fb1cb4c684.

Can you confirm please?

**Comment by sergiodxa** [comment]
@TooTallNate the trailing slash part it's fixed
