### ISSUE TITLE
Redirect POST/PUT/DELETE verbs

### ISSUE THREAD

**Issue by philcockfield** [now-examples/redirect#8]
The redirects seem to turn anything other that a GET into a GET.

eg. `POST https://url.com/foo` => `GET https://target.com/foo`

**Comment by TooTallNate** [comment]
It just does a standard 301 redirect, so the `GET` behavior is from the browser (and by spec).

If you really do want to redirect `POST` to the endpoint server, then you can use the 307 response code. i.e.

```
$ now now-examples/redirect --env STATUS=307 --env REDIRECT_URL=https://n8.io
```

See [here](https://softwareengineering.stackexchange.com/a/99966) for more information. Hope that helps!
